apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user_service
  name: user_service
  labels:
    app: user_service
spec:
  selector:
    matchLabels:
      app: user_service
  template:
    metadata:
      labels:
        app: user_service
        name: user_service
    spec:
      containers:
        - name: user_service
          image: pavan-intelops/user_management/user_service
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 4000
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        