apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user_management
  name: user_management
  labels:
    app: user_management
spec:
  selector:
    matchLabels:
      app: user_management
  template:
    metadata:
      labels:
        app: user_management
        name: user_management
    spec:
      containers:
        - name: user_management
          image: pavan-intelops/user_management/user_management
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 23234
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        